### ISSUE TITLE
Make an Admin Page for Managing Entries

### ISSUE THREAD

**Issue by tramyardg** [alvyn279/wi-find#13]
- [x] #17 Create a front end page for admin to do CRUD functionalities @tramyardg
 - [x] #14 Create a function to display entries @tramyardg
 - [x] #15 Create a function to delete entries @tramyardg
 - [ ] #16 Create a function to update entries @alvyn279 
 -  (optional) Create a function to create entries -> 
no need as you can create one using the client page

**Comment by tramyardg** [comment]
@alvyn279 let's use a JS MVC framework. What do you suggest?
